CREATE TABLE SaleItems (
SaleItemId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
SaleId UNIQUEIDENTIFIER NOT NULL,
ProductId UNIQUEIDENTIFIER NOT NULL,
Barcode NVARCHAR(50) NOT NULL,
Quantity INT NOT NULL,
UnitPrice DECIMAL(18,2) NOT NULL,
LineTotal DECIMAL(18,2) NOT NULL,
CONSTRAINT FK_SaleItems_Sales FOREIGN KEY (SaleId) REFERENCES Sales(SaleId)
);
