
CREATE TABLE Sales (
SaleId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
OutletId NVARCHAR(50) NOT NULL,
SaleDate DATETIME2 NOT NULL,
TotalAmount DECIMAL(18,2) NOT NULL,
SyncStatus NVARCHAR(20) NOT NULL,
RetryCount INT NOT NULL DEFAULT 0,
LastSyncAttemptAt DATETIME2 NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);