
CREATE TABLE Products (
ProductId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
Name NVARCHAR(150) NOT NULL,
Barcode NVARCHAR(50) NOT NULL UNIQUE,
StockQuantity INT NOT NULL,
Price DECIMAL(18,2) NOT NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);