
CREATE TABLE CentralSales (
SaleId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
OutletId NVARCHAR(50) NOT NULL,
SaleDate DATETIME2 NOT NULL,
TotalAmount DECIMAL(18,2) NOT NULL,
ReceivedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);